# This secret is used to set the initial credentials of the node container.
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Release.Namespace }}
type: "Opaque"
data:
  vmstore-csi-file-driver-config.yaml: {{ .Values.config | toYaml | b64enc }}
