# Take a new snapshot
#
# !!! Make sure to run nginx-dynamic-volume.yaml before running this example
# !!! Make sure to run snapshot-class.yaml before running this example
#
# $ kubectl apply -f examples/snapshot-from-dynamic.yaml
#

apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: snapshot-from-dynamic
spec:
  volumeSnapshotClassName: vmstore-csi-snapshot-class
  source:
    persistentVolumeClaimName: vmstore-csi-file-driver-pvc
    # kind: PersistentVolumeClaim
