# Create a new snapshot class

# $ kubectl apply -f examples/snapshot-class.yaml
#

apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: vmstore-csi-snapshot-class
driver: vmstore.csi.tintri.com
deletionPolicy: Delete
